core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import home_page_view, ticket_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('ticket/', ticket_view, name='ticket'),
    path('', home_page_view, name='home'),
    path('home/', home_page_view, name='landing'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path

from .views import profile_edit_view

urlpatterns = [
    path('edit', profile_edit_view, name='edit')
]

tickets/urls.py
from django.urls import path

from .views import ticket_home_view, ticket_detail_view, JitBitAPI, jitbit, ticket_create_view, load_subcategories

urlpatterns = [
    path('', ticket_home_view, name='home'),
    path('new', ticket_create_view, name='new'),
    path('ajax/load-subcategories', load_subcategories, name='ajax_load_subcategories' ),
    path('<int:id>', ticket_detail_view, name='detail'),
    path('jitbit', jitbit, name='jitbit')
]

templates/base/accounts.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>APL Helpdesk | {% block title %}{% endblock title %}</title>
    <meta content="" name="descriptison" />
    <meta content="" name="keywords" />
    <meta name="robots" content="NOINDEX, NOFOLLOW">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon" />
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>
  <body>
    {% block accounts %}
    {% endblock accounts %}
  </body>
</html>

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Ticket Desk</title>
    <meta content="" name="descriptison" />
    <meta content="" name="keywords" />
    <meta name="robots" content="NOINDEX, NOFOLLOW">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon" />
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon" />
    

    <!-- CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha512-xA6Hp6oezhjd6LiLZynuukm80f8BoZ3OpcEYaqKoCV3HKQDrYjDE1Gu8ocxgxoXmwmSzM4iqPvCsOkQNiu41GA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Externals -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <!-- =======================================================
    * Template Name: ALOPEX - Helpdesk - v1.0.0
    * Author: Johnny Whitworth
    * License: https://alopextech.com/license
    ======================================================== -->
  </head>
  <body>

      <section class="base">
        {% include 'base/navbar.html' %}
        {% include 'base/sidenav.html' %}
        <section class='main'>
            {% block content %}
            {% endblock content %}
        </section>
      </section>

    <!-- Vendor JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}
    <!-- JS File -->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

templates/base/navbar.html
<section class='navbar'>
    <div class="nav">
        <div class="header">
            <h3>TicketDesk - {{ user.profile.get_full_name }}</h3>
        </div>
        <div class="detail">
            <div class="section">
                <a href="{% url 'tickets:new' %}"><span class="material-icons">add</span></a>
            </div>
            <div class="section">
                <a href="?test=Division"><span class="material-icons">question_answer</span></a>
                <a href="?test=Division"><span class="material-icons">info</span></a>
                <a href="?test=Division"><span class="material-icons">settings</span></a>
            </div>
            <div class="section">
                <a href="{% url 'profiles:edit' %}"><span class="material-icons">account_circle</span></a>
            </div>
        </div>
    </div>

</section>

templates/base/sidenav.html
<section class='side-nav closed'>
    <div class="nav">
        <div class="detail">
            <ul>
                <li><a href="?test=Dashboard">
                    <span class="material-icons">dashboard</span>
                    <p>Dashboard</p></a>
                </li>
                <li><a href="?test=Desk" >
                    <span class="material-icons">switch_left</span>
                    <p class="hidden-item">Change Desk</p></a>
                    <ul class='dropdown'>
                        <li><a href="?test=Support">
                            <span class="material-icons">desktop_mac</span>
                            <p class="drop-item">Support</p></a>
                        </li>
                        <li><a href="?test=eCMS">
                            <span class="material-icons">groups</span>
                            <p class="drop-item">eCMS</p></a>
                        </li>
                        <li><a href="?test=Returns">
                            <span class="material-icons">devices</span>
                            <p class="drop-item">Returns</p></a>
                        </li>
                        <li><a href="?test=HR">
                            <span class="material-icons">badge</span>
                            <p class="drop-item">HR</p></a>
                        </li>
                        <li><a href="?test=Drones">
                            <span class="material-icons">center_focus_weak</span>
                            <p class="drop-item">Drones</p></a>
                        </li>
                    </ul>
                </li>
                <li><a href="http://localhost:8000/tickets/" class="active">
                    <span class="material-icons">label_important</span>
                    <p>Tickets</p></a>
                    <ul class="dropdown">
                        <li><a href="?test=New">
                            <span class="material-icons">description</span>
                            <p class="drop-item">New</p>
                        </a></li>
                        <li><a href="?test=Open">
                            <span class="material-icons">folder_open</span>
                            <p class="drop-item">Open</p>
                        </a></li>
                        <li><a href="?test=Closed">
                            <span class="material-icons">folder</span>
                            <p class="drop-item">Closed</p>
                        </a></li>
                        <li><a href="?test=New">
                            <span class="material-icons">description</span>
                            <p class="drop-item">New</p>
                        </a></li>
                        <li><a href="?test=Pending">
                            <span class="material-icons">update</span>
                            <p class="drop-item">Pending</p>
                        </a></li>
                    </ul>
                </li>
                <li><a href="?test=Alerts">
                    <span class="material-icons">chat</span>
                    <p>Alerts</p>
                </a></li>
                <li><a href="?test=Reports">
                    <span class="material-icons">leaderboard</span>
                    <p>Reports</p></a>
                    <ul class="dropdown">
                        <li><a href="?test=Tech">
                            <span class="material-icons">person</span>
                            <p class="drop-item">Technician</p>
                        </a></li>
                        <li><a href="?test=User">
                            <span class="material-icons">people</span>
                            <p class="drop-item">User</p>
                        </a></li>
                        <li><a href="?test=Reports">
                            <span class="material-icons">leaderboard</span>
                            <p class="drop-item">Reports</p>
                        </a></li>
                        <li><a href="?test=Division">
                            <span class="material-icons">business</span>
                            <p class="drop-item">Division</p>
                        </a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="detail">
            <ul>
                <li>
                    {% if user.is_authenticated %}
                    <a id="toggler" href="{% url 'account_logout' %}">
                    <span class="material-icons">logout</span>
                    <p>logout</p>
                    {% else %}
                    <a id="toggler" href="{% url 'account_login' %}">
                    <span class="material-icons">login</span>
                    <p>login</p>
                    {% endif %}
                </a></li>
                {% comment %} <li><a id="toggler" onclick="toggler()">
                    <span class="material-icons">menu</span>
                    <p>Collapse Menu</p>
                </a></li> {% endcomment %}
            </ul>
        </div>
    </div>
</section>

templates/base/title.html
<div class="title">
    <div class="header">
        <h2>{{ title }}</h2>
    </div>
    <div class="detail">
        <div class="set">
            <span class="material-icons">arrow_left</span>
            <span class="material-icons">arrow_right</span>
        </div>
        <div class="set">
            <span class="material-icons">cached</span>
        </div>
        <div class="set">
            <span class="material-icons">filter_alt</span>
        </div>
        <div class="set">
            <span class="material-icons">sort</span>
        </div>
    </div>
</div>