core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import home_page_view, ticket_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('ticket/', ticket_view, name='ticket'),
    path('', home_page_view, name='home'),
    path('home/', home_page_view, name='landing'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path

from .views import ticket_home_view, ticket_detail_view, JitBitAPI, jitbit, ticket_create_view, load_subcategories

urlpatterns = [
    path('', ticket_home_view, name='home'),
    path('new', ticket_create_view, name='new'),
    path('ajax/load-subcategories', load_subcategories, name='ajax_load_subcategories' ),
    path('<int:id>', ticket_detail_view, name='detail'),
    path('jitbit', jitbit, name='jitbit')
]

tickets/models.py
"""
alopex-helpdesk - A Django powered support desk

(c) Copyright Alopex Technologies LLC
All Rights Reserved. See LICENSE for details.

models.py - Model definitions.
"""

from django.contrib.auth.models import Permission
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _, ugettext
import mimetypes
import datetime
import re
import os
import uuid

from markdown import markdown
from markdown.extensions import Extension

from core import settings

def format_time_spent(time_spent):
    if time_spent:
        time_spent = "{0:02d}h:{1:02d}m".format(
            time_spent.seconds // 3600,
            time_spent.seconds // 60
        )
    else:
        time_spent = ""
    return time_spent

class EscapeHtml(Extension):
    def extend_markdown(self, md, md_globals):
        del md.preprocessors['html_block']
        del md.inlinePatterns['html']

def get_markdown(text):
    if not text:
        return ""
    return mark_safe(
        markdown(
            text,
            extensions=[
                EscapeHtml(), 'markdown.extensions.nl2br',
                'mardown.extensions.fenced_code'
            ]
        )
    )

class Container(models.Model):
    """
    A container is virutal standalone queue for tickets
    to allow for multiple departments to use autonomously
    """
    long_name = models.CharField(
        _('Long Name'),
        max_length=100,
    )
    short_name = models.CharField(
        _('Short Name'),
        max_length=50,
    )
    slug = models.SlugField(
        _('Slug'),
        max_length=50,
        unique=True,
    )
    email_address = models.EmailField(
        _('email Address'),
        blank=False,
        null=False,
    )
    new_ticket_cc = models.CharField(
        _('New Ticket CC Address'),
        blank=True,
        null=True,
        max_length=255,
    )
    updated_ticket_cc = models.CharField(
        _('Updated Ticket CC Address'),
        blank=True,
        null=True,
        max_length=255,
    )
    email_box = models.ForeignKey(
        'Email',
        on_delete=models.DO_NOTHING
    )
    dedicated_time = models.DurationField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return f'{self.short_name}'

    class Meta:
        ordering = ('long_name'),
        verbose_name = _('Container')
        verbose_name_plural = _('Containers')

    @property
    def time_spent(self):
        total = datetime.timedelta(0)
        for val in self.ticket_set.all():
            if val.time_spent:
                total = total + val.time_spent
        return total
    

class Email(models.Model):
    user = models.CharField(
        _('Email Username'),
        max_length=200,
        blank=False,
        null=False,
    )
    password = models.CharField(
        _('Email Password'),
        max_length=30,
        blank=False,
        null=False,
    )
    email_type = models.CharField(
        _('Email Type'),
        max_length=5,
        choices=(('pop3', _('POP 3')), ('imap', _('IMAP'))),
        blank=False,
        null=False,
        default='imap'
    )
    host = models.CharField(
        _('Host Name'),
        max_length=30,
        blank=False,
        null=False,
    )
    port = models.IntegerField(
        _('Email Port'),
        blank=False,
        null=False,
        default=993
    )
    ssl = models.BooleanField(
        _('Use SSL'),
        blank=False,
        null=False,
        default=True
    )
    folder = models.CharField(
        _('Email Folder'),
        max_length=30,
        blank=False,
        null=False,
    )
    retrieval_interval = models.IntegerField(
        _('Email Check Interval'),
        blank=True,
        null=True,
        default='5',
    )
    last_check = models.DateTimeField(
        blank=True,
        null=True,
        editable=False,
    )

    def save(self, *args, **kwargs):
        if not self.folder:
            self.folder = 'INBOX'
        super(Email, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.user}'


def mk_secret():
    return str(uuid.uuid4())


class Ticket(models.Model):

    NEW_STATUS = 0
    OPEN_STATUS = 1
    REOPENED_STATUS = 2
    RESOLVED_STATUS = 3
    CLOSED_STATUS = 4
    DUPLICATE_STATUS = 5

    STATUS_CHOICES = (
        (NEW_STATUS, _('New')),
        (OPEN_STATUS, _('Open')),
        (REOPENED_STATUS, _('Reopened')),
        (RESOLVED_STATUS, _('Resolved')),
        (CLOSED_STATUS, _('Closed')),
        (DUPLICATE_STATUS, _('Duplicate')),
    )

    PRIORITY_CHOICES = (
        (1, _('1. Critical')),
        (2, _('2. High')),
        (3, _('3. Normal')),
        (4, _('4. Low')),
        (5, _('5. Very Low')),
    )
    subject = models.CharField(
        _('Subject'),
        max_length=100,
        blank=True,
        null=True,
    )
    issue = models.CharField(
        _('Issue'),
        max_length=200,
        null=True,
        blank=True
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        verbose_name=_('Category')
    )
    subcategory = models.ForeignKey(
        'SubCategory',
        on_delete=models.CASCADE,
        verbose_name=_('Sub Category')
    )
    associated_employee = models.ForeignKey(
        'Employees',
        on_delete=models.CASCADE,
        verbose_name=_('Employees'),
        blank=True,
        null=True,
    )
    container = models.ForeignKey(
        'Container',
        on_delete=models.CASCADE,
        verbose_name=_('Container'),
    )
    created = models.DateTimeField(
        _('Created'),
        blank=True,
        default=timezone.now()
    )
    modified = models.DateTimeField(
        _('Modified'),
        blank=True,
    )
    submitter = models.ForeignKey(
        get_user_model(),
        related_name=_('submitter'),
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )
    technician = models.ForeignKey(
        get_user_model(),
        related_name=_('technician'),
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    division = models.CharField(
        verbose_name='Division',
        max_length=100,
        null=False,
        blank=False,
        default='None'
    )
    status = models.IntegerField(
        _('Status'),
        choices=STATUS_CHOICES,
        default=NEW_STATUS
    )
    resolution = models.TextField(
        _('Resolution'),
        blank=True,
        null=True,
    )
    priority = models.IntegerField(
        _('Priority'),
        choices=PRIORITY_CHOICES,
        default=3,
        blank=3,
    )
    due_date = models.DateTimeField(
        _('Due on'),
        blank=True,
        null=True,
    )
    secret_key = models.CharField(
        _('Secret key'),
        max_length=36,
        default=mk_secret
    )
    master_ticket = models.ForeignKey(
        'Ticket',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    @property
    def time_spent(self):
        """
        Returns back the total time spent on a ticket
        """
        total = datetime.timedelta(0)
        for val in self.comment_set.all():
            if val.time_spent:
                total = total + val.time_spent
        return total

    def _get_assigned_to(self):
        """
        Return assigned to tech, unassigned in none
        """
        if not self.technician:
            return _('Unassigned')
        else:
            return f'{self.technician}'
    get_assigned_to = property(_get_assigned_to)

    def _get_ticket(self):
        return u'[%s]' % (self.container.slug, self.id)
    ticket = property(_get_ticket)

    def _get_ticket_for_url(self):
        return u"%s-%s" % (self.queue.slug, self.id)
    ticket_for_url = property(_get_ticket_for_url)

    def _get_status_css_class(self):
        if self.status == 0:
            return 'new'
        elif self.status == 1:
            return 'open'
        elif self.status == 4:
            return 'closed'
    get_status_css_class = property(_get_status_css_class)

    def _get_priority_css_class(self):
        if self.priority == 2:
            return "warning"
        elif self.priority == 1:
            return "danger"
        elif self.priority == 5:
            return "success"
        else:
            return ""
    get_priority_css_class = property(_get_priority_css_class)

    class Meta:
        get_latest_by = "created"
        ordering = ('id',)
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')

    def __str__(self):
        return '%s %s' % (self.id, self.issue)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('tickets:detail', kwargs={"id": self.id})

    def save(self, *args, **kwargs):
        if not self.priority:
            self.priority = 3
        self.modified = timezone.now()

        if self.technician:
            self.status = 1

        if self.associated_employee:
            self.subject = f'{self.category} - {self.subcategory}({self.associated_employee})'
        else:
            self.subject = f'{self.category} - {self.subcategory}'
        self.division = self.submitter.profile.get_division_display()

        

        super(Ticket, self).save(*args, **kwargs)

    def get_markdown(self):
        return get_markdown(self.issue)

    @property
    def get_resolution_markdown(self):
        return get_markdown(self.resolution)


class Comment(models.Model):

    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        verbose_name=_('Ticket'),
        null=True,
        blank=True,
    )
    master_comment = models.ForeignKey(
        'Comment',
        on_delete=models.CASCADE,
        verbose_name=_('Master Comment'),
        null=True,

tickets/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import JsonResponse
from django.utils import timezone
import json, os, requests
from requests.auth import HTTPBasicAuth

from .models import Ticket, Category, Users, Container, Comment, SubCategory
from .forms import TicketForm

def ticket_home_view(request):
    template = 'tickets/home.html'
    title = 'Home'
    tickets = Ticket.objects.all()
    context = {
        'title': title,
        'tickets': tickets
    }
    return render(request, template, context)

def ticket_create_view(request):
    template = 'tickets/new.html'
    title='Create Ticket'
    container = Container.objects.get(id=1)
    
    form = TicketForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance = Ticket(
            container=container,
            issue=form.cleaned_data['issue'],
            category=form.cleaned_data['category'],
            subcategory=form.cleaned_data['subcategory'],
            associated_employee=form.cleaned_data['associated_employee'],
            created=timezone.now(),
            status=Ticket.NEW_STATUS,
            submitter=request.user,
            priority=3,
        )
        instance.save()
        return redirect('tickets:home')

    context = {
        'title': title,
        'form' : form,
    }

    return render(request, template, context)

def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = SubCategory.objects.filter(category_id=category_id).order_by('subcategory')
    return render(request, 'tickets/subcategory_dl_list.html', {'subcategories': subcategories})


def ticket_detail_view(request, id):
    template = 'tickets/ticket.html'
    ticket = Ticket.objects.get(id=id)
    comments = Comment.objects.filter(ticket=ticket)
    title = ticket.id

    context = {
        'title': title,
        'ticket': ticket,
        'comments': comments,
    }
    return render(request, template, context)

class JitBitAPI:

    def __init__(self):
        self.auth = HTTPBasicAuth(settings.HELPDESK_USER, settings.HELPDESK_PWD)

        if not self.test_creds():
            raise ValueError("Authorization failed, please check your credentials")
        else:
            print('Connection to Arizona Pipeline JitBit Established')

    def test_creds(self):
        """
        Ensure a connection to the JitBit API
        """
        response = self._make_request("Authorization")
        return response.status_code == 200

    def _make_request(self, method):
        """
        Default method for JitBit API calls
        """
        url = f'{settings.HELPDESK_URL}/api/{method}'
        print(url)
        return requests.get(url, auth=self.auth)

    def pull_tickets(self):
        """
        Retrieves all unclosed tickets from JitBit API
        """
        method = 'Tickets/?mode=unclosed&count=50'
        response = self._make_request(method)
        tickets = json.loads(response.content)
        return tickets

    def push_tickets(self, tickets=None):
        """
        Pushes pulled tickets into tickets db
        """
        pass

    def pull_comment(self, ticket):
        """
        Pull comments for a select ticket
        """
        method = f'comments?id={ticket}'
        response = self._make_request(method)
        comments = json.loads(response.content)
        return comments

    def push_comments(self):
        """
        Batch process push_comments to populate local db with all available tickets
        """
        pass

def jitbit(request):
    tickets = JitBitAPI().pull_tickets()
    return JsonResponse(tickets, safe=False)

templates/tickets/home.html
{% extends 'base/base.html' %}
{% block content %}
{% include 'base/title.html' %}
<div class="ticket-home">
    <div class="head">
        <p>ISSUE</p>
        <p>Category</p>
        <p>DIVISION</p>
        <p>USER</p>
        <p>TECH</p>
        <p>CREATED</p>
    </div>
    <div class="records">
    {% for ticket in tickets %}
        <div class="record" data-href='{{ ticket.get_absolute_url }}'>
            <p class="line {{ ticket.get_status_css_class }}">{{ ticket.subject }}</p>
            <p>{{ ticket.category }}</p>
            <p>{{ ticket.division }}</p>
            <p>{{ ticket.submitter }}</p>
            <p>{{ ticket.get_assigned_to }}</p>
            <p>{{ ticket.created|date:"M dS h:i A" }}</p>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

templates/tickets/new.html
{% extends 'base/base.html' %}
{% block content %}
{% include 'base/title.html' %}

<section class='main-form'>
    <div class="card">
        <div class="form"> 
            <form id="newTicketForm" method="post" data-subcategories-url="{% url 'tickets:ajax_load_subcategories' %}">
            {% csrf_token %}
                    {% comment %} <label for="category">Category</label> {% endcomment %}
                    {{ form.category }}
                    {% comment %} <label for="subcategory">Subcategory</label> {% endcomment %}
                    {{ form.subcategory }}
                    {{ form.associated_employee }}
                
                    {{ form.issue }}
                
                
                
                {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                        <p class="error-color t-center">{{ error|escape }}</p>
                    {% endfor %}
                    {% endfor %}
                {% endif %}
                <div class="submit">
                    <button type="submit">Create Ticket</button>
                </div>
            </form>
        </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_category").change(function () {
        var categoryId = $(this).val();
        var url = $('#newTicketForm').attr("data-subcategories-url");
        var employeeForm = $("#id_associated_employee");
        
        if (categoryId === '2') {
            employeeForm.removeClass('hidden')
        }
        else {
            employeeForm.addClass('hidden')
        }
        
        $.ajax ({
            url: url,
            data: {
                'category': categoryId
            },
            success: function (data) {
                $("#id_subcategory").html(data);
            }
        })
    });

    $("#id_subcategory").change(function () {
        console.log($(this).val())
        if ($(this).val() === '2') {
            console.log('here')
        }
    });
</script>
{% endblock content %}

templates/tickets/subcategory_dl_list.html
{% for sub in subcategories %}
<option value="{{ sub.pk }}">{{ sub.subcategory }}</option>
{% endfor %}

templates/tickets/ticket.html
{% extends 'base/base.html' %}
{% block content %}
<div class="title">
    <div class="header">
        <h2>Ticket: {{ title }} | {{ ticket.subject }}</h2>
    </div>
    <div class="detail">
        <div class="set">
            <span class="material-icons">arrow_left</span>
            <span class="material-icons">arrow_right</span>
        </div>
        <div class="set">
            <span class="material-icons">cached</span>
        </div>
        <div class="set">
            <span class="material-icons">filter_alt</span>
        </div>
        <div class="set">
            <span class="material-icons">sort</span>
        </div>
    </div>
</div>
<div class="tickets">
    <div class="container">
        <div class="left">
            <div class="message">
                <div class="card">
                    <div class="head col message">
                        <div class="status">
                            <h3>Ticket: {{ ticket.id }}</h3>
                            <p class="bar {{ ticket.get_status_css_class}}">{{ ticket.get_status_display }}</p>
                        </div>
                        <div class="subject">
                            <h3>{{ ticket.subject }}</h3>
                            <p>{{ ticket.issue }}</p>
                        </div>
                    </div>
                    <div class="footer">
                        <span class="material-icons button s-button bl-round">more_horiz</span>
                        <span class="material-icons button s-button">post_add</span>
                        <div class="button l-button">
                            <h3>Submitter</h3>
                            <p>{{ ticket.submitter }}</p>
                        </div>
                        <div class="button l-button">
                            <h3>Tech</h3>
                            <p>{{ ticket.get_assigned_to }}</p>
                        </div>
                        <div class="button l-button">
                            <h3>Division</h3>
                            <p>{{ ticket.division }}</p>
                        </div>
                        <div class="button l-button">
                            <h3>Category</h3>
                            <p>{{ ticket.category }}</p>
                        </div>
                        <div class="button l-button">
                            <h3>Date</h3>
                            <p>{{ ticket.created|date:"M dS h:i A" }}</p>
                        </div>
                        <span class="material-icons button s-button br-round">reply</span>
                    </div>
                </div>
            </div>
            <div class="label">
                <h3>Updates</h3>
            </div>
            <div class="button-group ul-buttons">
                <p class="button">Attachments</p>
                <p class="button active">Messages</p>
                <p class="button">Notes</p>
            </div>
            <div class="comments">
                {% for comment in comments %}
                <div class="comment">
                    <div class="card {% if comment.master_comment %}inline {% endif %}">
                        <div class="head col {% if comment.public %} bg-primary {% else %}{% endif %}">
                            <span class="material-icons">account_circle</span>
                            <div class="info">
                                <h3>{{ comment.user }}</h3>
                                <p>{{ comment.date|date:"M dS h:i A" }}</p>
                            </div>
                        </div>
                        <div class="body">
                            <p>{{ comment }}</p>
                        </div>
                        <div class="footer">
                            <span class="material-icons button s-button bl-round">email</span>
                            <div class="info">
                                <p>{% if comment.public %}Tech only {% endif %}</p>
                                <p></p>
                            </div>
                            <span class="material-icons button s-button">add</span>
                            <span class="material-icons button s-button br-round">reply</span>
                        </div>
                    </div>
                </div>
                {% endfor%}
            </div>
        </div>
        <div class="right">
            <div class="info">
                <div class="card">
                    <div class="head bg-primary">
                        <h3>Tech Tickets</h3>
                    </div>
                    <div class="body round">
                        <p class="button">New Device - iPhone (16043)</p>
                        <p class="button">New Device - Laptop (17407)</p>
                        <p class="button">New Device - iPad (16009)</p>
                        <p class="button">New Device - iPad (14261)</p>
                        <p class="button">New Device - iPad (14262)</p>
                        <p class="button">New Device - iPad (14263)</p>
                        <p class="button">New Device - iPad (14260)</p>
                        <p class="button">New Device - iPhone (14260)</p>
                    </div>
                </div>
                <div class="card">
                    <div class="head bg-primary">
                        <h3>User Tickets</h3>
                    </div>
                    <div class="body round">
                        <p class="button">New Device - iPhone (16043)</p>
                        <p class="button">New Device - iPhone (17424)</p>
                        <p class="button">New Device - iPad (17424)</p>
                        <p class="button">New Device - iPad (14260)</p>
                        <p class="button">New Device - iPhone (14260)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}